apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    app: client
  name: client-deployment
spec:
  replicas: 3  # Number of desired replicas
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: frontend-container
          image: 083118395813.dkr.ecr.ap-south-1.amazonaws.com/client-image:latest
          ports:
            - containerPort: 3000
